/**
 * YScript 语言元数据：关键字、类型、内置函数。
 * 供 LSP 补全、悬停、签名帮助使用。
 */

export type CompletionKind =
  | 'keyword' | 'type' | 'constant' | 'builtin' | 'method'
  | 'property' | 'snippet'
  | 'function' | 'variable' | 'field' | 'class'
  | 'struct' | 'enum' | 'interface' | 'module';

export interface CompletionItemMeta {
  label: string;
  kind: CompletionKind;
  detail: string;
  insertText?: string;
  sortKey?: number;
  /** method/property 属于哪个类型 */
  of?: string;
  /** 函数签名（签名帮助用），缺省时由 insertText/label 推导 */
  signature?: string;
  /** 更详细的文档说明（markdown 用），缺省时回退到 detail */
  documentation?: string;
}

export const KEYWORDS: CompletionItemMeta[] = [
  { label: 'let', kind: 'keyword', detail: '声明块级变量', insertText: 'let ${1:name} = ${0:value}', sortKey: 10 },
  { label: 'var', kind: 'keyword', detail: '声明函数内局部变量（顶层不可用）', insertText: 'var ${1:name} = ${0:value}', sortKey: 10 },
  { label: 'infer', kind: 'snippet', detail: '使用 <- 声明并自动推断变量类型', insertText: '${1:name} <- ${0:value}', sortKey: 5 },
  { label: 'const', kind: 'keyword', detail: '声明编译期常量', insertText: 'const ${1:NAME} = ${0:value}', sortKey: 10 },
  { label: 'func', kind: 'keyword', detail: '函数定义', insertText: 'func ${1:name}(${2:args}) {\n\t${0}\n}', sortKey: 10 },
  { label: 'init', kind: 'keyword', detail: '自动初始化（main前执行）', insertText: 'init() {\n\t${0}\n}', sortKey: 10 },
  { label: 'main', kind: 'keyword', detail: '程序入口，必须有 func main()', sortKey: 10 },
  { label: 'struct', kind: 'keyword', detail: '结构体定义', insertText: 'struct ${1:Name} {\n\t${2:field}: ${3:type}\n}', sortKey: 10 },
  { label: 'extends', kind: 'keyword', detail: '继承父结构体（Java 风格多态）', insertText: 'extends ${1:Parent}', sortKey: 10 },
  { label: 'super', kind: 'keyword', detail: '调用最近祖先的同名方法实现（仅 struct 方法内）', sortKey: 12 },
  { label: 'enum', kind: 'keyword', detail: '枚举定义', insertText: 'enum ${1:Name} {\n\t${0}\n}', sortKey: 10 },
  { label: 'interface', kind: 'keyword', detail: '接口定义（鸭子类型，无需 implements）', insertText: 'interface ${1:Name} {\n\t${0}\n}', sortKey: 10 },
  { label: 'class', kind: 'keyword', detail: '类定义（与 struct 同构，可有方法与继承）', insertText: 'class ${1:Name} {\n\t${0}\n}', sortKey: 10 },
  { label: 'namespace', kind: 'keyword', detail: '命名空间声明', insertText: 'namespace ${1:Name}', sortKey: 10 },
  { label: 'using', kind: 'keyword', detail: '引入命名空间到当前作用域', insertText: 'using ${1:Name}', sortKey: 10 },
  { label: 'map', kind: 'keyword', detail: 'map 推导（生成映射结构）', insertText: 'map ${1:key} => ${0:value}', sortKey: 10 },
  { label: 'warp', kind: 'keyword', detail: '启动并发线程（await 取回结果）', insertText: 'let ${1:h} = warp {\n\t${0}\n}\n${1:h}.await()', sortKey: 10 },
  { label: 'if', kind: 'keyword', detail: '条件判断', insertText: 'if ${1:cond} {\n\t${0}\n}', sortKey: 10 },
  { label: 'else', kind: 'keyword', detail: '否则分支', sortKey: 11 },
  { label: 'elif', kind: 'keyword', detail: 'else if 简写', sortKey: 11 },
  { label: 'for', kind: 'keyword', detail: 'for 循环', insertText: 'for ${1:item} in ${2:list} {\n\t${0}\n}', sortKey: 10 },
  { label: 'while', kind: 'keyword', detail: '条件循环', insertText: 'while ${1:cond} {\n\t${0}\n}', sortKey: 10 },
  { label: 'loop', kind: 'keyword', detail: '无限循环（=while true）', insertText: 'loop {\n\t${0}\n}', sortKey: 10 },
  { label: 'break', kind: 'keyword', detail: '跳出循环', sortKey: 12 },
  { label: 'continue', kind: 'keyword', detail: '跳过本次循环', sortKey: 12 },
  { label: 'return', kind: 'keyword', detail: '函数返回（支持多值）', insertText: 'return ${0:value}', sortKey: 12 },
  { label: 'yield', kind: 'keyword', detail: '生成器暂停点', sortKey: 12 },
  { label: 'match', kind: 'keyword', detail: '模式匹配（支持多值/范围）', insertText: 'match ${1:val} {\n\t${2:pattern} => { ${3:body} }\n\t_ => { ${0:default} }\n}', sortKey: 10 },
  { label: 'switch', kind: 'keyword', detail: 'C风格switch分支', insertText: 'switch ${1:val} {\n\tcase ${2:pat}: { ${3:body} }\n\tdefault: { ${0} }\n}', sortKey: 10 },
  { label: 'case', kind: 'keyword', detail: 'switch 分支', sortKey: 11 },
  { label: 'default', kind: 'keyword', detail: '默认分支', sortKey: 11 },
  { label: 'panic', kind: 'keyword', detail: '抛出致命错误', insertText: 'panic("${0:msg}")', sortKey: 12 },
  { label: 'recover', kind: 'keyword', detail: 'defer内捕获panic', sortKey: 12 },
  { label: 'try', kind: 'keyword', detail: '传统错误处理保护区（优先用 expr catch）', insertText: 'try {\n\t${0}\n}', sortKey: 10 },
  { label: 'catch', kind: 'keyword', detail: '异常保护区 / 单行兜底 expr catch 默认值', insertText: 'catch {\n\t${0}\n}', sortKey: 10 },
  { label: 'finally', kind: 'keyword', detail: '传统错误处理清理块（优先用 ensure）', sortKey: 11 },
  { label: 'ensure', kind: 'keyword', detail: '无论是否异常都执行的清理块', insertText: 'ensure {\n\t${0}\n}', sortKey: 10 },
  { label: 'raise', kind: 'keyword', detail: '主动抛出异常', insertText: 'raise ${1:ErrorType}("${0:msg}")', sortKey: 12 },
  { label: 'assert', kind: 'keyword', detail: '断言（false则panic）', insertText: 'assert ${1:cond}', sortKey: 12 },
  { label: 'defer', kind: 'keyword', detail: '延迟执行（函数返回时执行）', insertText: 'defer func() {\n\t${0}\n}()', sortKey: 12 },
  { label: 'goto', kind: 'keyword', detail: '跳转到标签', sortKey: 12 },
  { label: 'import', kind: 'keyword', detail: '导入模块（标准库必须先导入才能使用）', insertText: 'import "${1:string}"', sortKey: 10 },
  { label: 'import 列表', kind: 'keyword', detail: '导入多个模块', insertText: 'import [\n\t"${1:string}",\n\t"${2:io}",\n]', sortKey: 10 },
  { label: 'package', kind: 'keyword', detail: '声明包名', insertText: 'package ${1:main}', sortKey: 10 },
  { label: 'as', kind: 'keyword', detail: '模块别名 / 类型转换', sortKey: 11 },
  { label: 'and', kind: 'keyword', detail: '逻辑与（短路求值）', sortKey: 13 },
  { label: 'or', kind: 'keyword', detail: '逻辑或（短路求值）', sortKey: 13 },
  { label: 'not', kind: 'keyword', detail: '逻辑非', sortKey: 13 },
  { label: 'xor', kind: 'keyword', detail: '逻辑异或', sortKey: 13 },
  { label: 'in', kind: 'keyword', detail: '成员包含判断: x in list', sortKey: 13 },
  { label: 'is', kind: 'keyword', detail: '类型判断: v is int', sortKey: 13 },
  { label: 'matches', kind: 'keyword', detail: '正则匹配', sortKey: 13 },
  { label: 'this', kind: 'keyword', detail: '方法内引用当前实例', sortKey: 12 },
  { label: 'true', kind: 'constant', detail: '布尔真', sortKey: 14 },
  { label: 'false', kind: 'constant', detail: '布尔假', sortKey: 14 },
  { label: 'nil', kind: 'constant', detail: '空值（引用类型默认值）', sortKey: 14 },
  { label: 'nan', kind: 'constant', detail: '非数字', sortKey: 14 },
  { label: 'inf', kind: 'constant', detail: '无穷大', sortKey: 14 },
];

export const TYPES: CompletionItemMeta[] = [
  { label: 'byte', kind: 'type', detail: '8 位无符号整数；byte(x) 校验 0..255，变量注解不自动转换' },
  { label: 'char', kind: 'type', detail: '单个Unicode字符' },
  { label: 'short', kind: 'type', detail: '16 位有符号整数用途注解；运行时以 int64 保存' },
  { label: 'ushort', kind: 'type', detail: '16 位无符号；ushort(x) 校验 0..65535，变量注解不自动转换' },
  { label: 'int', kind: 'type', detail: '64 位有符号整数' },
  { label: 'uint', kind: 'type', detail: '64 位无符号整数；uint(x) 拒绝负值' },
  { label: 'long', kind: 'type', detail: '64 位有符号整数' },
  { label: 'ulong', kind: 'type', detail: '64 位无符号整数；完整支持 0..2^64-1' },
  { label: 'float', kind: 'type', detail: '浮点数；运行时使用 float64' },
  { label: 'double', kind: 'type', detail: '浮点数；运行时使用 float64' },
  { label: 'bool', kind: 'type', detail: '布尔: true / false' },
  { label: 'string', kind: 'type', detail: '不可变UTF-8字符串' },
  { label: 'bytes', kind: 'type', detail: '原始字节序列 — Shellcode、数据包' },
  { label: 'list', kind: 'type', detail: '动态数组 list<T>', insertText: 'list<${1:T}>' },
  { label: 'dict', kind: 'type', detail: '哈希表 dict<K,V>', insertText: 'dict<${1:K}, ${2:V}>' },
  { label: 'ipv4', kind: 'type', detail: 'IPv4地址（语法糖）' },
  { label: 'ipv6', kind: 'type', detail: 'IPv6地址（语法糖）' },
  { label: 'error', kind: 'type', detail: '错误类型' },
  { label: 'any', kind: 'type', detail: '任意类型' },
  // ── FFI / C 互操作类型（用于 c.bind / ffi.bind 的签名声明）─────────
  { label: 'void', kind: 'type', detail: 'FFI：无返回值', of: 'ffi' },
  { label: 'int8', kind: 'type', detail: 'FFI：C 的 int8_t（8位有符号）', of: 'ffi' },
  { label: 'uint8', kind: 'type', detail: 'FFI ABI：C uint8_t；结果保留为 unsigned 脚本整数', of: 'ffi' },
  { label: 'int16', kind: 'type', detail: 'FFI：C 的 int16_t（16位有符号）', of: 'ffi' },
  { label: 'uint16', kind: 'type', detail: 'FFI ABI：C uint16_t；结果保留为 unsigned 脚本整数', of: 'ffi' },
  { label: 'int32', kind: 'type', detail: 'FFI：C 的 int（32位有符号，注意不是 64 位）', of: 'ffi' },
  { label: 'uint32', kind: 'type', detail: 'FFI ABI：C unsigned int；结果保留为 unsigned 脚本整数', of: 'ffi' },
  { label: 'int64', kind: 'type', detail: 'FFI：C 的 int64_t', of: 'ffi' },
  { label: 'uint64', kind: 'type', detail: 'FFI ABI：C uint64_t；结果可表示完整 uint64 范围', of: 'ffi' },
  { label: 'clong', kind: 'type', detail: 'FFI：C 的 long — 宽度随平台而变（Linux 8 / Windows 4 字节）', of: 'ffi' },
  { label: 'culong', kind: 'type', detail: 'FFI：C 的 unsigned long — 宽度随平台而变', of: 'ffi' },
  { label: 'ptr', kind: 'type', detail: 'FFI：指针（整数当地址用，配合 c.malloc / ffi.alloc）', of: 'ffi' },
  { label: 'cstring', kind: 'type', detail: 'FFI：C 字符串 const char*（传 YScript 字符串自动补 \\0）', of: 'ffi' },
  { label: 'struct:', kind: 'type', detail: 'FFI：结构体按值传，如 struct:int32,double', of: 'ffi', insertText: 'struct:${1:int32},${2:double}' },
];

export const BUILTIN_FUNCTIONS: CompletionItemMeta[] = [
  // 基础 I/O
  { label: 'breakpoint', kind: 'builtin', detail: '在此处暂停（仅在调试器运行时可用）', insertText: 'breakpoint()' },
  { label: 'print', kind: 'builtin', detail: '输出到stdout（不换行）', insertText: 'print(${0})' },
  { label: 'println', kind: 'builtin', detail: '输出到stdout（换行）', insertText: 'println(${0})' },
  { label: 'printf', kind: 'builtin', detail: '格式化输出', insertText: 'printf("${1:fmt}", ${0})' },
  { label: 'sprintf', kind: 'builtin', detail: '格式化返回字符串', insertText: 'sprintf("${1:fmt}", ${0})' },

  // 类型/元
  { label: 'len', kind: 'builtin', detail: '返回长度: string/bytes/list/dict' },
  { label: 'type', kind: 'builtin', detail: '返回类型名: type(v) → "int"' },
  { label: 'eval', kind: 'builtin', detail: '动态执行代码字符串' },
  { label: 'next', kind: 'builtin', detail: '从生成器取下一个值' },
  { label: 'hex', kind: 'builtin', detail: '转为十六进制: hex(255) → "0xff"' },

  // 类型转换
  { label: 'string', kind: 'builtin', detail: '转为字符串' },
  { label: 'int', kind: 'builtin', detail: '转为整数' },
  { label: 'float', kind: 'builtin', detail: '转为浮点' },
  { label: 'bool', kind: 'builtin', detail: '转为布尔' },
  { label: 'byte', kind: 'builtin', detail: '转为单字节' },
  { label: 'bytes', kind: 'builtin', detail: '转为字节序列' },
  { label: 'char', kind: 'builtin', detail: '转为单字符' },

  // IP 地址
  { label: 'ipv4', kind: 'builtin', detail: '构造IPv4: ipv4("192.168.1.1")', insertText: 'ipv4("${1}")' },
  { label: 'ipv6', kind: 'builtin', detail: '构造IPv6: ipv6("::1")', insertText: 'ipv6("${1}")' },

  // 错误
  { label: 'panic', kind: 'builtin', detail: '抛出致命错误', insertText: 'panic("${0}")' },
  { label: 'recover', kind: 'builtin', detail: 'defer内捕获panic' },
  { label: 'assert', kind: 'builtin', detail: '断言（false则panic）', insertText: 'assert ${0}' },

  // === 命名空间速查（高频） ===
  { label: 'io.NewBufferedReader', kind: 'builtin', detail: '创建缓冲 Reader', signature: 'io.NewBufferedReader(reader, size?)', documentation: '包装 reader handle；size 默认 4096。' },
  { label: 'io.NewBufferedWriter', kind: 'builtin', detail: '创建缓冲 Writer', signature: 'io.NewBufferedWriter(writer, size?)', documentation: '包装 writer handle；调用 io.Flush 或 io.Close 刷新缓冲。' },
  { label: 'io.NewBufferedReadWriter', kind: 'builtin', detail: '创建缓冲读写句柄', signature: 'io.NewBufferedReadWriter(reader, writer, size?)' },
  { label: 'io.Peek', kind: 'builtin', detail: '预读但不消费字节', signature: 'io.Peek(reader, n) -> bytes' },
  { label: 'io.ReaderDiscard', kind: 'builtin', detail: '从缓冲 Reader 丢弃指定字节', signature: 'io.ReaderDiscard(reader, n) -> int' },
  { label: 'io.ReaderBuffered', kind: 'builtin', detail: '缓冲 Reader 中可读字节数' },
  { label: 'io.ReaderSize', kind: 'builtin', detail: '缓冲 Reader 的容量' },
  { label: 'io.ReaderReset', kind: 'builtin', detail: '将缓冲 Reader 切换到新数据源' },
  { label: 'io.ReadRune', kind: 'builtin', detail: '读取一个 Unicode 码点', documentation: '返回 {rune: 码点整数, size: UTF-8 字节数}。' },
  { label: 'io.UnreadRune', kind: 'builtin', detail: '撤销最近一次 ReadRune' },
  { label: 'io.UnreadByte', kind: 'builtin', detail: '撤销最近一次字节读取' },
  { label: 'io.ReadLine', kind: 'builtin', detail: '读取一行或行片段', documentation: '返回 {line: bytes, is_prefix: bool}；is_prefix 为 true 时继续读取。' },
  { label: 'io.ReadSlice', kind: 'builtin', detail: '读到单字节分隔符', signature: 'io.ReadSlice(reader, delimiter) -> bytes' },
  { label: 'io.ReadBytes', kind: 'builtin', detail: '读到分隔符并返回 bytes' },
  { label: 'io.ReadString', kind: 'builtin', detail: '读到分隔符并返回 string' },
  { label: 'io.ReaderWriteTo', kind: 'builtin', detail: '将 Reader 剩余内容写入 Writer' },
  { label: 'io.Buffered', kind: 'builtin', detail: '查询句柄缓冲数据量', documentation: 'ReadWriter 优先返回 Reader 缓冲量；分别查询请用 ReaderBuffered / WriterBuffered。' },
  { label: 'io.WriterBuffered', kind: 'builtin', detail: '缓冲 Writer 中待写字节数' },
  { label: 'io.WriterSize', kind: 'builtin', detail: '缓冲 Writer 的容量' },
  { label: 'io.WriterReset', kind: 'builtin', detail: '切换缓冲 Writer 的输出目标并丢弃未刷新数据' },
  { label: 'io.Available', kind: 'builtin', detail: '缓冲 Writer 剩余容量' },
  { label: 'io.Flush', kind: 'builtin', detail: '刷新缓冲 Writer 并返回底层写入错误' },
  { label: 'io.WriteByte', kind: 'builtin', detail: '向缓冲 Writer 写入一个字节' },
  { label: 'io.WriteRune', kind: 'builtin', detail: '向缓冲 Writer 写入一个 Unicode 码点' },
  { label: 'io.ReadFrom', kind: 'builtin', detail: '将 Reader 内容读入缓冲 Writer' },
  { label: 'io.NewScanner', kind: 'builtin', detail: '创建 token Scanner', signature: 'io.NewScanner(reader, split?, initial?, max?)', documentation: 'split 可选 lines / words / bytes / runes，默认 lines。' },
  { label: 'io.ScannerScan', kind: 'builtin', detail: '读取 Scanner 下一个 token' },
  { label: 'io.ScannerText', kind: 'builtin', detail: '获取当前 Scanner token 字符串' },
  { label: 'io.ScannerBytes', kind: 'builtin', detail: '获取当前 Scanner token 字节' },
  { label: 'io.ScannerErr', kind: 'builtin', detail: '获取 Scanner 最后一个错误' },
  { label: 'io.ScannerBuffer', kind: 'builtin', detail: '设置 Scanner token 缓冲区', documentation: '必须在首次 ScannerScan 前调用。' },
  { label: 'io.ScannerSplit', kind: 'builtin', detail: '设置 Scanner 分割规则', documentation: '支持 lines / words / bytes / runes，必须在首次 ScannerScan 前调用。' },
  { label: 'io.ErrFinalToken', kind: 'builtin', detail: 'Scanner split 结束标记错误' },
  { label: 'io.ScanLines', kind: 'builtin', detail: '返回 Scanner 按行分割规则' },
  { label: 'io.ScanWords', kind: 'builtin', detail: '返回 Scanner 按空白分割规则' },
  { label: 'io.ScanBytes', kind: 'builtin', detail: '返回 Scanner 按字节分割规则' },
  { label: 'io.ScanRunes', kind: 'builtin', detail: '返回 Scanner 按 Unicode 码点分割规则' },
  { label: 'io.read_file', kind: 'builtin', detail: '读取文本文件→string' },
  { label: 'io.read_bytes', kind: 'builtin', detail: '读取二进制文件→bytes' },
  { label: 'io.write_file', kind: 'builtin', detail: '覆盖写入文件' },
  { label: 'io.append_file', kind: 'builtin', detail: '追加写入文件' },
  { label: 'io.file_exists', kind: 'builtin', detail: '路径是否存在' },
  { label: 'io.is_file', kind: 'builtin', detail: '是否为普通文件' },
  { label: 'io.is_dir', kind: 'builtin', detail: '是否为目录' },
  { label: 'io.walk', kind: 'builtin', detail: '递归遍历目录' },
  { label: 'io.mkdir', kind: 'builtin', detail: '创建单层目录' },
  { label: 'io.mkdir_all', kind: 'builtin', detail: '递归创建多层目录' },
  { label: 'io.read_dir', kind: 'builtin', detail: '读取目录内容' },
  { label: 'io.copy', kind: 'builtin', detail: '复制文件' },
  { label: 'io.rename', kind: 'builtin', detail: '移动/重命名文件' },
  { label: 'io.remove', kind: 'builtin', detail: '删除文件/空目录' },
  { label: 'io.remove_all', kind: 'builtin', detail: '递归删除' },
  { label: 'io.chmod', kind: 'builtin', detail: '修改文件权限' },
  { label: 'io.temp_file', kind: 'builtin', detail: '创建临时文件' },
  { label: 'io.temp_dir', kind: 'builtin', detail: '创建临时目录' },
  { label: 'io.symlink', kind: 'builtin', detail: '创建软链接' },
  { label: 'io.readlink', kind: 'builtin', detail: '读取软链接目标' },

  { label: 'load.load', kind: 'builtin', detail: '加载 YScript 函数模块并返回导出字典' },
  { label: 'load.reload', kind: 'builtin', detail: '重新编译并替换已加载模块' },
  { label: 'load.unload', kind: 'builtin', detail: '卸载模块并清空导出字典' },
  { label: 'load.loaded', kind: 'builtin', detail: '列出当前已加载模块路径' },

  { label: 'path.join', kind: 'builtin', detail: '拼接路径' },
  { label: 'path.basename', kind: 'builtin', detail: '取文件名' },
  { label: 'path.dirname', kind: 'builtin', detail: '取目录部分' },
  { label: 'path.ext', kind: 'builtin', detail: '取扩展名: .bin' },
  { label: 'path.stem', kind: 'builtin', detail: '无扩展名文件名' },
  { label: 'path.is_abs', kind: 'builtin', detail: '是否绝对路径' },
  { label: 'path.abs', kind: 'builtin', detail: '转为绝对路径' },

  { label: 'json.parse', kind: 'builtin', detail: '解析JSON→dict/list' },
  { label: 'json.stringify', kind: 'builtin', detail: '序列化为JSON' },
  { label: 'json.pretty_print', kind: 'builtin', detail: '漂亮格式输出' },
  { label: 'json.from_file', kind: 'builtin', detail: '从文件读取JSON' },
  { label: 'json.to_file', kind: 'builtin', detail: '写入JSON到文件' },
  { label: 'json.query', kind: 'builtin', detail: 'JSONPath查询: $.path' },

  { label: 'regex.match', kind: 'builtin', detail: '正则是否匹配' },
  { label: 'regex.find', kind: 'builtin', detail: '查找第一个匹配' },
  { label: 'regex.find_all', kind: 'builtin', detail: '查找全部匹配' },
  { label: 'regex.replace', kind: 'builtin', detail: '正则替换' },

  { label: 'encoding.base64_encode', kind: 'builtin', detail: 'Base64编码' },
  { label: 'encoding.base64_decode', kind: 'builtin', detail: 'Base64解码' },
  { label: 'encoding.hex_encode', kind: 'builtin', detail: '十六进制编码' },
  { label: 'encoding.hex_decode', kind: 'builtin', detail: '十六进制解码' },
  { label: 'encoding.url_encode', kind: 'builtin', detail: 'URL编码' },
  { label: 'encoding.url_decode', kind: 'builtin', detail: 'URL解码' },

  { label: 'crypto.MD5', kind: 'builtin', detail: 'MD5哈希' },
  { label: 'crypto.SHA1', kind: 'builtin', detail: 'SHA1哈希' },
  { label: 'crypto.SHA224', kind: 'builtin', detail: 'SHA224哈希' },
  { label: 'crypto.SHA256', kind: 'builtin', detail: 'SHA256哈希' },
  { label: 'crypto.SHA384', kind: 'builtin', detail: 'SHA384哈希' },
  { label: 'crypto.SHA512', kind: 'builtin', detail: 'SHA512哈希' },
  { label: 'crypto.SHA512_224', kind: 'builtin', detail: 'SHA512/224哈希' },
  { label: 'crypto.SHA512_256', kind: 'builtin', detail: 'SHA512/256哈希' },
  { label: 'crypto.SHA3_224', kind: 'builtin', detail: 'SHA3-224哈希' },
  { label: 'crypto.SHA3_256', kind: 'builtin', detail: 'SHA3-256哈希' },
  { label: 'crypto.SHA3_384', kind: 'builtin', detail: 'SHA3-384哈希' },
  { label: 'crypto.SHA3_512', kind: 'builtin', detail: 'SHA3-512哈希' },
  { label: 'crypto.BLAKE2s', kind: 'builtin', detail: 'BLAKE2s哈希' },
  { label: 'crypto.BLAKE2b', kind: 'builtin', detail: 'BLAKE2b哈希' },
  { label: 'crypto.HMAC_SHA256', kind: 'builtin', detail: 'HMAC-SHA256' },
  { label: 'crypto.HMAC_SHA3_256', kind: 'builtin', detail: 'HMAC-SHA3-256' },
  { label: 'crypto.HMAC_SHA3_384', kind: 'builtin', detail: 'HMAC-SHA3-384' },
  { label: 'crypto.HMAC_SHA3_512', kind: 'builtin', detail: 'HMAC-SHA3-512' },
  { label: 'crypto.HMAC_SHA512', kind: 'builtin', detail: 'HMAC-SHA512' },

  { label: 'ocr.recognize', kind: 'builtin', detail: '识别图片字节', signature: 'ocr.recognize(image, lang?, psm?, whitelist?)', documentation: '使用 Tesseract 识别内存中的图片；默认语言 eng、PSM 6。' },
  { label: 'ocr.from_file', kind: 'builtin', detail: '识别图片文件', signature: 'ocr.from_file(path, lang?, psm?, whitelist?)', documentation: '读取 PNG/JPEG/TIFF 等图片文件并返回识别文本。' },
  { label: 'ocr.set_lang', kind: 'builtin', detail: '设置默认 OCR 语言' },
  { label: 'ocr.get_lang', kind: 'builtin', detail: '读取默认 OCR 语言' },
  { label: 'ocr.set_psm', kind: 'builtin', detail: '设置默认页面分割模式' },
  { label: 'ocr.get_psm', kind: 'builtin', detail: '读取默认页面分割模式' },

  { label: 'aes.Encrypt', kind: 'builtin', detail: 'AES加密(CBC/CTR)' },
  { label: 'aes.Decrypt', kind: 'builtin', detail: 'AES解密' },
  { label: 'aes.RandomKey', kind: 'builtin', detail: '生成随机AES密钥' },

  { label: 'rsa.GenerateKeyPair', kind: 'builtin', detail: '生成RSA密钥对' },
  { label: 'rsa.Encrypt', kind: 'builtin', detail: 'RSA加密' },
  { label: 'rsa.Decrypt', kind: 'builtin', detail: 'RSA解密' },
  { label: 'rsa.Sign', kind: 'builtin', detail: 'RSA签名' },
  { label: 'rsa.Verify', kind: 'builtin', detail: 'RSA验证' },

  { label: 'net.DialTCP', kind: 'builtin', detail: 'TCP连接' },
  { label: 'net.DialTimeout', kind: 'builtin', detail: '带超时连接' },
  { label: 'net.DialUDP', kind: 'builtin', detail: 'UDP连接' },
  { label: 'net.Listen', kind: 'builtin', detail: '监听端口' },
  { label: 'net.Nginx', kind: 'builtin', detail: 'HTTP/HTTPS/PHP 静态目录服务', signature: 'net.Nginx(root, addr?, indexFile?, options?)', insertText: 'net.Nginx("${1:./public}", "${2::8080}", "${3:index.html}")', documentation: '自动发现 PATH 中的 php-cgi；也可用 options.php_cgi 指定。根目录无 index.html 时会执行 index.php。options.tls 可指定 PEM cert/key；access_log/access_log_file 可启用请求日志。返回 {root, addr, port, scheme, wait, stop}。' },
  { label: 'net.nginx', kind: 'builtin', detail: 'HTTP/HTTPS/PHP 静态目录服务', signature: 'net.nginx(root, addr?, indexFile?, options?)', insertText: 'net.nginx("${1:./public}", "${2::8080}", "${3:index.html}")', documentation: '自动发现 PATH 中的 php-cgi；也可用 options.php_cgi 指定。根目录无 index.html 时会执行 index.php。options.tls 可指定 PEM cert/key；access_log/access_log_file 可启用请求日志。返回 {root, addr, port, scheme, wait, stop}。' },
  { label: 'cli.New', kind: 'builtin', detail: '创建命令行参数解析器', signature: 'cli.New(name?, desc?)', insertText: 'cli.New("${1:app}", "${2:description}")', documentation: '支持 --long / -s / -abc / -cvalue 等参数语法；app.color(...) 设置参数名颜色，app.description_color(...) 可独立设置参数说明颜色，两者都支持 color 预设色和 RGB。' },
  { label: 'cli.Parse', kind: 'builtin', detail: '直接解析 argv 列表', signature: 'cli.Parse(argv?)', insertText: 'cli.Parse(${1:args})', documentation: 'argv 可传 list<string>，缺省时使用 os.Args[1:]。' },
  { label: 'net.dial_tcp', kind: 'builtin', detail: '建立TCP连接 → conn对象(read/read_line/write/set_timeout/close)' },
  { label: 'net.dial', kind: 'builtin', detail: '通用拨号 net.dial("tcp"|"udp", addr)' },
  { label: 'net.listen_tcp', kind: 'builtin', detail: '监听TCP → listener(accept/close)' },
  { label: 'net.udp_bind', kind: 'builtin', detail: '绑定UDP端口 → 套接字(recv_from/send_to/close)' },
  { label: 'net.udp_dial', kind: 'builtin', detail: '已连接UDP套接字(write/read/recv_from/send_to)' },
  { label: 'net.dial_udp', kind: 'builtin', detail: '同 udp_dial' },
  // ── HTTP 客户端（net/http，v0.1.5.1 扩展）────────────────────
  { label: 'http.Get', kind: 'builtin', detail: 'HTTP GET http.Get(url, body?, opts?)', documentation: 'opts 支持 headers/timeout/json/form/files/cookies/retries/dump 等；传输失败默认返回 null' },
  { label: 'http.Head', kind: 'builtin', detail: 'HTTP HEAD http.Head(url, opts?)' },
  { label: 'http.Post', kind: 'builtin', detail: 'HTTP POST http.Post(url, body?, opts?)' },
  { label: 'http.Put', kind: 'builtin', detail: 'HTTP PUT http.Put(url, body?, opts?)' },
  { label: 'http.Patch', kind: 'builtin', detail: 'HTTP PATCH http.Patch(url, body?, opts?)' },
  { label: 'http.Delete', kind: 'builtin', detail: 'HTTP DELETE http.Delete(url, body?, opts?)' },
  { label: 'http.Options', kind: 'builtin', detail: 'HTTP OPTIONS http.Options(url, opts?)' },
  { label: 'http.Do', kind: 'builtin', detail: '通用请求 http.Do(method, url, body?, opts?)' },
  { label: 'http.Request', kind: 'builtin', detail: '同 http.Do（别名）' },
  { label: 'http.Form', kind: 'builtin', detail: '表单提交 http.Form(url, fields, opts?)', documentation: '自动设置 Content-Type: application/x-www-form-urlencoded' },
  { label: 'http.Upload', kind: 'builtin', detail: 'multipart 上传 http.Upload(url, files, fields?, opts?)', documentation: 'files: {"file": 路径 或 {path,name,content_type}}，自动带 boundary' },
  { label: 'http.Download', kind: 'builtin', detail: '下载到文件 http.Download(url, path, opts?) → resp', documentation: '404 等非 2xx 不写文件；成功返回 {status,path,size,...}' },
  { label: 'http.Dump', kind: 'builtin', detail: '构造原始请求报文(不发送) http.Dump(method, url, body?, opts?)' },
  { label: 'http.Query', kind: 'builtin', detail: 'dict → 查询串(键排序、URL转义) http.Query({q: "a b"})' },
  { label: 'http.Session', kind: 'builtin', detail: '创建会话 http.Session({base_url, headers, ...})', documentation: '会话共享 Cookie 与默认配置，可链式调用 s.get(...)/s.post(...)' },
  { label: 'http.Headers', kind: 'builtin', detail: '取响应头 http.Headers(resp, name?)', documentation: '不给 name 返回全部头 dict；名字大小写不敏感，缺失返回 null' },
  { label: 'http.Body', kind: 'builtin', detail: '取响应体文本 http.Body(resp)' },
  { label: 'http.Raw', kind: 'builtin', detail: '原始响应报文(类似 Burp Raw) http.Raw(resp)' },
  { label: 'http.StatusText', kind: 'builtin', detail: '状态码释义 http.StatusText(404|resp)' },
  { label: 'http.StatusCode', kind: 'builtin', detail: '状态码释义(详细) http.StatusCode(404|resp)', documentation: '比 StatusText 更详细，含分类(信息/成功/重定向/客户端错误/服务端错误)与说明' },
  { label: 'http.Ok', kind: 'builtin', detail: '响应是否成功(2xx) http.Ok(resp)' },
  { label: 'http.Json', kind: 'builtin', detail: '解析响应 JSON http.Json(resp)' },
  { label: 'http.Cookie', kind: 'builtin', detail: '读响应 Set-Cookie http.Cookie(resp, name?)' },
  { label: 'http.Cookies', kind: 'builtin', detail: '响应全部 Cookie → dict http.Cookies(resp)' },
  { label: 'http.Insecure', kind: 'builtin', detail: '开关 TLS 证书校验 http.Insecure(false)' },
  { label: 'http.SetTimeout', kind: 'builtin', detail: '全局超时(秒) http.SetTimeout(15)' },
  { label: 'http.SetProxy', kind: 'builtin', detail: '全局代理 http.SetProxy("http://127.0.0.1:8080")' },
  { label: 'http.SetUserAgent', kind: 'builtin', detail: '全局 User-Agent http.SetUserAgent(ua)' },
  { label: 'http.SetHeader', kind: 'builtin', detail: '全局请求头 http.SetHeader(name, value)' },
  { label: 'http.SetRedirects', kind: 'builtin', detail: '最大重定向次数 http.SetRedirects(5)' },
  { label: 'http.SetCookie', kind: 'builtin', detail: '全局 Cookie http.SetCookie(name, value)' },
  { label: 'http.ClearCookies', kind: 'builtin', detail: '清空全局 Cookie' },
  { label: 'http.ClearHeaders', kind: 'builtin', detail: '清空全局请求头' },
  { label: 'http.SetRetries', kind: 'builtin', detail: '全局重试次数 http.SetRetries(3)', documentation: '仅对 429/500/502/503/504 重试，退避 2^n 秒' },
  { label: 'http.SetRetryDelay', kind: 'builtin', detail: '首次重试间隔(秒) http.SetRetryDelay(0.5)' },
  { label: 'http.SetRetryBackoff', kind: 'builtin', detail: '重试退避策略 http.SetRetryBackoff("exp"|"linear"|"constant")' },
  { label: 'http.SetMaxBody', kind: 'builtin', detail: '响应体上限(字节) http.SetMaxBody(65536)', documentation: '超出截断并在响应里标记 truncated=true' },
  { label: 'http.SetRaise', kind: 'builtin', detail: '传输失败改为抛错 http.SetRaise(true)' },
  { label: 'http.BasicAuth', kind: 'builtin', detail: '全局 Basic 认证 http.BasicAuth(user, pass)' },
  { label: 'http.LastError', kind: 'builtin', detail: '最近一次传输错误 http.LastError()' },
  { label: 'http.SetAfterResponse', kind: 'builtin', detail: '注册全局响应后钩子 http.SetAfterResponse(fn)', documentation: 'fn 接受 resp dict 返回 dict；返回非 dict 不替换，可用于日志/二次加工' },
  { label: 'http.Server', kind: 'builtin', detail: '启动 HTTP 服务 http.Server(addr, handler) → server', documentation: 'addr 形如 ":8080" 或 "127.0.0.1:0"；handler(req) dict,返回 {status,headers?,body?}' },
  { label: 'http.Reset', kind: 'builtin', detail: '恢复全部全局默认配置 http.Reset()' },
  { label: 'net.LookupHost', kind: 'builtin', detail: 'DNS正向解析' },
  { label: 'net.LookupMX', kind: 'builtin', detail: 'DNS MX记录' },
  { label: 'net.LookupNS', kind: 'builtin', detail: 'DNS NS记录' },
  { label: 'net.CIDR', kind: 'builtin', detail: 'CIDR子网计算' },

  { label: 'ssl.GetServerCertificate', kind: 'builtin', detail: '获取服务器TLS证书' },
  { label: 'ssl.ParseCertificate', kind: 'builtin', detail: '解析X.509证书' },
  { label: 'ssl.Connect', kind: 'builtin', detail: '建立TLS连接' },

  { label: 'yaml.parse', kind: 'builtin', detail: '解析YAML' },
  { label: 'yaml.from_file', kind: 'builtin', detail: '从文件读取YAML' },
  { label: 'toml.parse', kind: 'builtin', detail: '解析TOML' },
  { label: 'toml.from_file', kind: 'builtin', detail: '从文件读取TOML' },
  { label: 'ini.parse', kind: 'builtin', detail: '解析INI' },
  { label: 'ini.from_file', kind: 'builtin', detail: '从文件读取INI' },

  { label: 'sync.Mutex', kind: 'builtin', detail: '创建互斥锁' },
  { label: 'sync.RWMutex', kind: 'builtin', detail: '创建读写锁' },
  { label: 'sync.Chan', kind: 'builtin', detail: '创建通道' },
  { label: 'sync.try_recv', kind: 'builtin', detail: '非阻塞接收；空队列返回 nil' },
  { label: 'sync.Semaphore', kind: 'builtin', detail: '创建信号量(n)' },
  { label: 'sync.Atomic', kind: 'builtin', detail: '创建原子变量(init)' },
  { label: 'sync.WaitGroup', kind: 'builtin', detail: '创建等待组' },
  { label: 'sync.WorkerPool', kind: 'builtin', detail: '创建工作池(n)' },
  { label: 'sync.Once', kind: 'builtin', detail: '一次性初始化（do 只执行一次）' },
  { label: 'sync.Cond', kind: 'builtin', detail: '条件变量（wait/signal/broadcast）' },
  { label: 'sync.TLS', kind: 'builtin', detail: '线程局部存储（set/get/del/clear）' },
  { label: 'sync.select', kind: 'builtin', detail: '通道选择（无default阻塞）', insertText: 'sync.select(sync.case(${1:ch}, ${2:fn}))' },
  { label: 'sync.case', kind: 'builtin', detail: 'select 分支: 通道+回调' },
  { label: 'sync.default', kind: 'builtin', detail: 'select 非阻塞默认分支' },

  { label: 'time.now', kind: 'builtin', detail: '当前时间' },
  { label: 'time.format', kind: 'builtin', detail: '格式化: "2006-01-02 15:04:05"' },
  { label: 'time.parse', kind: 'builtin', detail: '解析时间字符串' },
  { label: 'time.duration', kind: 'builtin', detail: '持续时间: time.duration("5s")' },
  { label: 'time.new_timer', kind: 'builtin', detail: '一次性计时器' },
  { label: 'time.new_ticker', kind: 'builtin', detail: '周期性定时器' },

  { label: 'rand.int', kind: 'builtin', detail: '随机整数 [min,max]' },
  { label: 'rand.string', kind: 'builtin', detail: '随机字符串: rand.string(16,"alnum")' },
  { label: 'rand.bytes', kind: 'builtin', detail: '随机字节: rand.bytes(32)' },
  { label: 'rand.choice', kind: 'builtin', detail: '从列表中随机选' },
  { label: 'rand.uuid', kind: 'builtin', detail: 'UUID v4' },

  { label: 'sys.cpu_info', kind: 'builtin', detail: 'CPU信息' },
  { label: 'sys.mem_info', kind: 'builtin', detail: '内存信息' },
  { label: 'sys.net_interfaces', kind: 'builtin', detail: '网络接口列表' },
  { label: 'sys.process_list', kind: 'builtin', detail: '进程列表' },
  { label: 'sys.process_info', kind: 'builtin', detail: '进程详情' },
  { label: 'sys.find_process', kind: 'builtin', detail: '按名查找进程' },
  { label: 'sys.kill_process', kind: 'builtin', detail: '终止进程' },

  { label: 'os.exec', kind: 'builtin', detail: '执行外部程序' },
  { label: 'os.shell', kind: 'builtin', detail: '通过Shell执行' },
  { label: 'os.exit', kind: 'builtin', detail: '退出进程' },
  { label: 'os.sleep', kind: 'builtin', detail: '暂停: "2s"/"500ms"' },
  { label: 'os.getpid', kind: 'builtin', detail: '当前进程ID' },
  { label: 'os.getenv', kind: 'builtin', detail: '读取环境变量' },
  { label: 'os.setenv', kind: 'builtin', detail: '设置环境变量' },
  { label: 'os.environ', kind: 'builtin', detail: '所有环境变量(dict)' },
  { label: 'os.hostname', kind: 'builtin', detail: '主机名' },

  { label: 'log.debug', kind: 'builtin', detail: 'DEBUG级别日志' },
  { label: 'log.info', kind: 'builtin', detail: 'INFO级别日志' },
  { label: 'log.warn', kind: 'builtin', detail: 'WARN级别日志' },
  { label: 'log.error', kind: 'builtin', detail: 'ERROR级别日志' },
  { label: 'log.set_level', kind: 'builtin', detail: '设置日志级别' },
  { label: 'log.get_level', kind: 'builtin', detail: '当前日志级别名称' },
  { label: 'log.log', kind: 'builtin', detail: '动态级别输出 log.log("WARN", msg...)' },
  { label: 'log.set_output', kind: 'builtin', detail: '输出目标 stderr/stdout/file/both(+path)' },
  { label: 'log.set_rotate', kind: 'builtin', detail: '按大小轮转 set_rotate(max_bytes, keep)' },
  { label: 'log.set_color', kind: 'builtin', detail: '彩色级别标签开关' },
  { label: 'log.set_ts', kind: 'builtin', detail: '时间戳开关' },
  { label: 'log.set_json', kind: 'builtin', detail: 'JSON Lines 模式开关' },
  { label: 'log.flush', kind: 'builtin', detail: '刷盘' },
  { label: 'log.close', kind: 'builtin', detail: '关闭日志文件并回到 stderr' },

  // === socket（TCP/UDP/TLS 统一对象，失败抛带类型异常）===
  { label: 'socket.Socket', kind: 'builtin', detail: '创建套接字 socket.Socket("tcp"|"udp")', insertText: 'socket.Socket("${1|tcp,udp|}")' },
  { label: 'socket.tcp_request', kind: 'builtin', detail: '一行TCP请求（服务端须主动关闭）' },
  { label: 'socket.udp_request', kind: 'builtin', detail: '一行UDP请求 → [数据, 来源地址]' },
  { label: 'socket.tls_request', kind: 'builtin', detail: '一行TLS请求' },
  { label: 'socket.tcp_probe', kind: 'builtin', detail: '探测TCP端口是否开放' },
  { label: 'socket.port_scan', kind: 'builtin', detail: '扫描端口（返回开放端口列表）' },
  { label: 'socket.default_timeout', kind: 'builtin', detail: '查询/设置默认超时毫秒' },

  { label: 'stdio.input', kind: 'builtin', detail: '提示+读取一行' },
  { label: 'stdio.prompt', kind: 'builtin', detail: '带默认值的输入' },
  { label: 'stdio.confirm', kind: 'builtin', detail: 'y/n确认' },
  { label: 'stdio.select', kind: 'builtin', detail: '多选一菜单' },
  { label: 'stdio.clear', kind: 'builtin', detail: '清屏' },

  { label: 'color.Red', kind: 'builtin', detail: '红色' },
  { label: 'color.Green', kind: 'builtin', detail: '绿色' },
  { label: 'color.Yellow', kind: 'builtin', detail: '黄色' },
  { label: 'color.RGB', kind: 'builtin', detail: '自定义RGB(r,g,b)' },
  { label: 'color.Println', kind: 'builtin', detail: '带颜色打印+换行' },

  { label: 'reflect.type_of', kind: 'builtin', detail: '获取类型名' },
  { label: 'reflect.fields', kind: 'builtin', detail: '获取struct字段列表' },
  { label: 'reflect.to_json', kind: 'builtin', detail: 'struct→JSON' },
  { label: 'reflect.from_json', kind: 'builtin', detail: 'JSON→struct' },

  { label: 'errors.new', kind: 'builtin', detail: '创建错误' },
  { label: 'errors.new_with_code', kind: 'builtin', detail: '创建带错误码的错误' },
  { label: 'errors.wrap', kind: 'builtin', detail: '包装错误（添加上下文）' },

  { label: 'ffi.open', kind: 'builtin', detail: '加载.so/.dll动态库' },
  { label: 'ffi.bind', kind: 'builtin', detail: '绑定C函数到变量' },
  { label: 'ffi.call', kind: 'builtin', detail: '调用C函数（真实ABI，0-8参数）' },
  { label: 'ffi.find', kind: 'builtin', detail: '查找符号（配合 ffi.call）' },
  { label: 'ffi.alloc', kind: 'builtin', detail: '分配真实C堆内存' },
  { label: 'ffi.free', kind: 'builtin', detail: '释放 ffi.alloc 内存' },
  { label: 'ffi.read', kind: 'builtin', detail: '从真实内存地址读 n 字节' },
  { label: 'ffi.write', kind: 'builtin', detail: '向真实内存地址写字节' },
  { label: 'ffi.str', kind: 'builtin', detail: '读取真实内存中的 C 字符串' },

  { label: 'cuda.device_count', kind: 'builtin', detail: 'GPU设备数' },
  { label: 'cuda.MD5_Batch', kind: 'builtin', detail: 'GPU批量MD5' },
  { label: 'cuda.SHA256_Batch', kind: 'builtin', detail: 'GPU批量SHA256' },
  { label: 'cuda.NTLM_Batch', kind: 'builtin', detail: 'GPU批量NTLM' },
  { label: 'cuda.WPA2_PMK_Batch', kind: 'builtin', detail: 'GPU批量WPA2 PMK' },
  { label: 'regex.replace_fn', kind: 'builtin', detail: '正则回调替换: (pat, str, fn)' },
  { label: 'array.Map', kind: 'builtin', detail: '列表变换（支持用户函数）' },
  { label: 'array.Filter', kind: 'builtin', detail: '列表过滤（支持用户函数）' },
  { label: 'array.Reduce', kind: 'builtin', detail: '列表聚合（支持用户函数）' },
  { label: 'iter.map', kind: 'builtin', detail: '迭代变换' },
  { label: 'iter.filter', kind: 'builtin', detail: '迭代过滤' },
  { label: 'iter.take', kind: 'builtin', detail: '取前n个' },
  { label: 'iter.chain', kind: 'builtin', detail: '串联多个迭代' },
  { label: 'time.new_timer', kind: 'builtin', detail: '一次性计时器(ms): wait/ready/stop' },
  { label: 'time.new_ticker', kind: 'builtin', detail: '周期性定时器(ms): wait/stop' },
  { label: 'raw.PcapOpen', kind: 'builtin', detail: '打开设备实时抓包' },
  { label: 'raw.PcapNext', kind: 'builtin', detail: '读取下一包（超时返回nil）' },
  { label: 'raw.PcapFilter', kind: 'builtin', detail: '设置BPF过滤器' },
  { label: 'raw.PcapClose', kind: 'builtin', detail: '关闭抓包句柄' },
  { label: 'raw.PcapReadFile', kind: 'builtin', detail: '读取.pcap文件' },
  { label: 'raw.PcapWriteFile', kind: 'builtin', detail: '写入.pcap文件' },
];

export const TYPE_MEMBERS: CompletionItemMeta[] = [
  // === string methods ===
  { of: 'string', label: 'contains', kind: 'method', detail: '是否包含子串' },
  { of: 'string', label: 'index', kind: 'method', detail: '首次出现位置' },
  { of: 'string', label: 'last_index', kind: 'method', detail: '末次出现位置' },
  { of: 'string', label: 'count', kind: 'method', detail: '出现次数' },
  { of: 'string', label: 'has_prefix', kind: 'method', detail: '是否以..开头' },
  { of: 'string', label: 'has_suffix', kind: 'method', detail: '是否以..结尾' },
  { of: 'string', label: 'replace', kind: 'method', detail: '替换（首个）' },
  { of: 'string', label: 'replace_all', kind: 'method', detail: '全部替换' },
  { of: 'string', label: 'split', kind: 'method', detail: '按分隔符分割' },
  { of: 'string', label: 'split_lines', kind: 'method', detail: '按行分割' },
  { of: 'string', label: 'join', kind: 'method', detail: '用分隔符拼接列表' },
  { of: 'string', label: 'trim', kind: 'method', detail: '去首尾字符' },
  { of: 'string', label: 'trim_prefix', kind: 'method', detail: '去前缀' },
  { of: 'string', label: 'trim_suffix', kind: 'method', detail: '去后缀' },
  { of: 'string', label: 'lower', kind: 'method', detail: '转小写' },
  { of: 'string', label: 'upper', kind: 'method', detail: '转大写' },
  { of: 'string', label: 'capitalize', kind: 'method', detail: '首字母大写' },
  { of: 'string', label: 'rune_len', kind: 'method', detail: 'Unicode 码点数量（区别于 UTF-8 字节长度 len）' },
  { of: 'string', label: 'char_at', kind: 'method', detail: '按 Unicode 码点取字符，支持负索引', insertText: 'char_at(${1:index})' },
  { of: 'string', label: 'slice', kind: 'method', detail: '按 Unicode 码点切片，支持负边界', insertText: 'slice(${1:start}, ${2:end})' },
  { of: 'string', label: 'pad_left', kind: 'method', detail: '按码点宽度左填充，可循环多字符填充串', insertText: 'pad_left(${1:width}, "${2: }")' },
  { of: 'string', label: 'pad_right', kind: 'method', detail: '按码点宽度右填充，可循环多字符填充串', insertText: 'pad_right(${1:width}, "${2: }")' },
  { of: 'string', label: 'repeat', kind: 'method', detail: '重复n次' },
  { of: 'string', label: 'to_int', kind: 'method', detail: '严格转换为整数，允许首尾空白' },
  { of: 'string', label: 'to_float', kind: 'method', detail: '严格转换为浮点数，允许首尾空白' },
  { of: 'string', label: 'matches', kind: 'method', detail: '正则匹配' },
  { of: 'string', label: 'find', kind: 'method', detail: '正则查找' },
  { of: 'string', label: 'find_all', kind: 'method', detail: '正则查找全部' },
  { of: 'string', label: 'len', kind: 'property', detail: '字符串长度(只读)' },
  { of: 'string', label: 'is_empty', kind: 'property', detail: '是否为空' },

  // === bytes methods ===
  { of: 'bytes', label: 'contains', kind: 'method', detail: '是否包含子字节' },
  { of: 'bytes', label: 'index', kind: 'method', detail: '首次出现位置' },
  { of: 'bytes', label: 'replace', kind: 'method', detail: '替换' },
  { of: 'bytes', label: 'replace_all', kind: 'method', detail: '全部替换' },
  { of: 'bytes', label: 'split', kind: 'method', detail: '按分隔符分割' },
  { of: 'bytes', label: 'chunk', kind: 'method', detail: '固定大小分块' },
  { of: 'bytes', label: 'to_hex', kind: 'method', detail: '转十六进制字符串' },
  { of: 'bytes', label: 'to_base64', kind: 'method', detail: '转Base64字符串' },
  { of: 'bytes', label: 'to_utf8', kind: 'method', detail: '转UTF-8字符串' },
  { of: 'bytes', label: 'pad_right', kind: 'method', detail: '右侧填充' },
  { of: 'bytes', label: 'pad_left', kind: 'method', detail: '左侧填充' },
  { of: 'bytes', label: 'truncate', kind: 'method', detail: '截断' },

  // === dict methods ===
  { of: 'dict', label: 'get', kind: 'method', detail: '取值(带默认): d.get("k", def)' },
  { of: 'dict', label: 'set', kind: 'method', detail: '设置键值' },
  { of: 'dict', label: 'delete', kind: 'method', detail: '删除键' },
  { of: 'dict', label: 'has', kind: 'method', detail: '是否包含键' },
  { of: 'dict', label: 'keys', kind: 'method', detail: '所有键列表' },
  { of: 'dict', label: 'values', kind: 'method', detail: '所有值列表' },
  { of: 'dict', label: 'items', kind: 'method', detail: '键值对列表' },
  { of: 'dict', label: 'merge', kind: 'method', detail: '合并另一dict' },
  { of: 'dict', label: 'copy', kind: 'method', detail: '深拷贝' },
  { of: 'dict', label: 'headers', kind: 'method', detail: 'HTTP响应头(仅HTTP响应有效)' },
  { of: 'dict', label: 'body', kind: 'method', detail: 'HTTP响应体(仅HTTP响应有效)' },
  { of: 'dict', label: 'raw', kind: 'method', detail: '完整原始HTTP响应(仅HTTP响应有效)' },
  { of: 'dict', label: 'clear', kind: 'method', detail: '清空' },
  { of: 'dict', label: 'size', kind: 'property', detail: '键值对数量(只读)' },
  { of: 'dict', label: 'empty', kind: 'property', detail: '是否为空(只读)' },

  // === list methods ===
  { of: 'list', label: 'append', kind: 'method', detail: '末尾添加' },
  { of: 'list', label: 'prepend', kind: 'method', detail: '开头添加' },
  { of: 'list', label: 'insert', kind: 'method', detail: '指定位置插入' },
  { of: 'list', label: 'pop', kind: 'method', detail: '弹出' },
  { of: 'list', label: 'remove', kind: 'method', detail: '按值删除' },
  { of: 'list', label: 'sort', kind: 'method', detail: '排序(升序)' },
  { of: 'list', label: 'sort_by', kind: 'method', detail: '自定义排序' },
  { of: 'list', label: 'reverse', kind: 'method', detail: '反转' },
  { of: 'list', label: 'map', kind: 'method', detail: '对每个元素做变换' },
  { of: 'list', label: 'filter', kind: 'method', detail: '过滤元素' },
  { of: 'list', label: 'reduce', kind: 'method', detail: '累积' },
  { of: 'list', label: 'flat', kind: 'method', detail: '展平嵌套列表' },
  { of: 'list', label: 'unique', kind: 'method', detail: '去重' },
  { of: 'list', label: 'copy', kind: 'method', detail: '浅拷贝' },
  { of: 'list', label: 'clear', kind: 'method', detail: '清空' },
  { of: 'list', label: 'len', kind: 'property', detail: '元素数量(只读)' },
  { of: 'list', label: 'empty', kind: 'property', detail: '是否为空(只读)' },
  { of: 'list', label: 'first', kind: 'property', detail: '第一个元素(只读)' },
  { of: 'list', label: 'last', kind: 'property', detail: '最后一个元素(只读)' },

  // === ipv4 members ===
  { of: 'ipv4', label: 'string', kind: 'property', detail: 'IP字符串(只读)' },
  { of: 'ipv4', label: 'is_private', kind: 'property', detail: '是否私有IP(只读)' },
  { of: 'ipv4', label: 'is_loopback', kind: 'property', detail: '是否回环(只读)' },
  { of: 'ipv4', label: 'is_multicast', kind: 'property', detail: '是否组播(只读)' },
  { of: 'ipv4', label: 'is_global', kind: 'property', detail: '是否全球IP(只读)' },
  { of: 'ipv4', label: 'version', kind: 'property', detail: 'IP版本: 4(只读)' },

  // === ipv6 members ===
  { of: 'ipv6', label: 'string', kind: 'property', detail: 'IP字符串(只读)' },
  { of: 'ipv6', label: 'expanded', kind: 'property', detail: '展开格式(只读)' },
  { of: 'ipv6', label: 'is_loopback', kind: 'property', detail: '是否回环(只读)' },
  { of: 'ipv6', label: 'is_private', kind: 'property', detail: '是否私有(只读)' },
  { of: 'ipv6', label: 'version', kind: 'property', detail: 'IP版本: 6(只读)' },

  // === warp handle members ===
  { of: 'warp', label: 'await', kind: 'method', detail: '等待结束并返回结果' },
  { of: 'warp', label: 'detach', kind: 'method', detail: '分离线程（主线程退出不等待）' },
  { of: 'warp', label: 'hush', kind: 'method', detail: '请求停止' },
  { of: 'warp', label: 'snap', kind: 'method', detail: '强制停止' },
  { of: 'warp', label: 'living', kind: 'method', detail: '是否存活' },
  { of: 'warp', label: 'link', kind: 'method', detail: '连锁：子线程停止时自身停止' },
  { of: 'warp', label: 'unlink', kind: 'method', detail: '取消连锁' },

  // === socket members ===
  { of: 'socket', label: 'connect', kind: 'method', detail: '连接(host, port)，失败抛 ConnectError' },
  { of: 'socket', label: 'listen', kind: 'method', detail: '监听端口（0 = 由内核分配），返回实际端口' },
  { of: 'socket', label: 'accept', kind: 'method', detail: '接受连接 → 新的 Socket' },
  { of: 'socket', label: 'bind', kind: 'method', detail: '绑定地址与端口（UDP）' },
  { of: 'socket', label: 'connect_udp', kind: 'method', detail: '连接UDP并固定源端口（收包前必须先调用）' },
  { of: 'socket', label: 'send', kind: 'method', detail: '发送数据' },
  { of: 'socket', label: 'recv', kind: 'method', detail: '接收数据（bytes）' },
  { of: 'socket', label: 'recv_all', kind: 'method', detail: '接收全部数据直到对端关闭' },
  { of: 'socket', label: 'recv_line', kind: 'method', detail: '接收一行（\\n 结尾）' },
  { of: 'socket', label: 'sendto', kind: 'method', detail: 'UDP 发送到指定地址' },
  { of: 'socket', label: 'recvfrom', kind: 'method', detail: 'UDP 接收 → [数据, 来源地址]' },
  { of: 'socket', label: 'send_addr', kind: 'method', detail: '按地址发送' },
  { of: 'socket', label: 'set_timeout', kind: 'method', detail: '设置超时（毫秒）' },
  { of: 'socket', label: 'set_option', kind: 'method', detail: '设置套接字选项' },
  { of: 'socket', label: 'set_nonblocking', kind: 'method', detail: '切换非阻塞模式' },
  { of: 'socket', label: 'set_insecure', kind: 'method', detail: '跳过 TLS 证书校验' },
  { of: 'socket', label: 'start_tls', kind: 'method', detail: '升级为 TLS 连接' },
  { of: 'socket', label: 'close', kind: 'method', detail: '关闭连接' },
  { of: 'socket', label: 'is_closed', kind: 'method', detail: '是否已关闭(只读)' },
  { of: 'socket', label: 'local_addr', kind: 'property', detail: '本地地址(只读)' },
  { of: 'socket', label: 'local_port', kind: 'property', detail: '本地端口(只读)' },
  { of: 'socket', label: 'peer_addr', kind: 'property', detail: '对端地址(只读)' },
  { of: 'socket', label: 'peer_port', kind: 'property', detail: '对端端口(只读)' },

  // === sync.Mutex members ===
  { of: 'sync.Mutex', label: 'lock', kind: 'method', detail: '加锁' },
  { of: 'sync.Mutex', label: 'unlock', kind: 'method', detail: '解锁（未持有时安全忽略）' },
  { of: 'sync.Mutex', label: 'try_lock', kind: 'method', detail: '非阻塞加锁，抢不到返回 false' },
  { of: 'sync.Mutex', label: 'locked', kind: 'method', detail: '当前是否已被锁定(只读)' },

  // === sync.RWMutex members ===
  { of: 'sync.RWMutex', label: 'lock', kind: 'method', detail: '写锁' },
  { of: 'sync.RWMutex', label: 'unlock', kind: 'method', detail: '释放写锁' },
  { of: 'sync.RWMutex', label: 'rlock', kind: 'method', detail: '读锁（可并发）' },
  { of: 'sync.RWMutex', label: 'runlock', kind: 'method', detail: '释放读锁' },

  // === sync.Once members ===
  { of: 'sync.Once', label: 'do', kind: 'method', detail: '只执行一次' },

  // === sync.Cond members ===
  { of: 'sync.Cond', label: 'wait', kind: 'method', detail: '等待通知' },
  { of: 'sync.Cond', label: 'signal', kind: 'method', detail: '唤醒一个等待者' },
  { of: 'sync.Cond', label: 'broadcast', kind: 'method', detail: '唤醒全部等待者' },

  // === sync.Semaphore members ===
  { of: 'sync.Semaphore', label: 'acquire', kind: 'method', detail: '获取一个许可（阻塞）' },
  { of: 'sync.Semaphore', label: 'release', kind: 'method', detail: '释放一个许可' },
  { of: 'sync.Semaphore', label: 'try_acquire', kind: 'method', detail: '非阻塞获取许可' },

  // === sync.Atomic members ===
  { of: 'sync.Atomic', label: 'load', kind: 'method', detail: '读取当前值' },
  { of: 'sync.Atomic', label: 'store', kind: 'method', detail: '写入新值' },
  { of: 'sync.Atomic', label: 'add', kind: 'method', detail: '原子加' },
  { of: 'sync.Atomic', label: 'sub', kind: 'method', detail: '原子减' },
  { of: 'sync.Atomic', label: 'swap', kind: 'method', detail: '交换并返回旧值' },
  { of: 'sync.Atomic', label: 'compare_and_swap', kind: 'method', detail: 'CAS：相等则写入并返回 true' },

  // === sync.Chan members ===
  { of: 'sync.Chan', label: 'send', kind: 'method', detail: '发送并阻塞' },
  { of: 'sync.Chan', label: 'recv', kind: 'method', detail: '接收并阻塞' },
  { of: 'sync.Chan', label: 'try_recv', kind: 'method', detail: '非阻塞接收，空队列返回 nil' },
  { of: 'sync.Chan', label: 'close', kind: 'method', detail: '关闭通道' },
  { of: 'sync.Chan', label: 'len', kind: 'property', detail: '队列长度(只读)' },
  { of: 'sync.Chan', label: 'cap', kind: 'property', detail: '队列容量(只读)' },

  // === sync.TLS members ===
  { of: 'sync.TLS', label: 'set', kind: 'method', detail: '设置线程局部变量' },
  { of: 'sync.TLS', label: 'get', kind: 'method', detail: '读取线程局部变量' },
  { of: 'sync.TLS', label: 'del', kind: 'method', detail: '删除线程局部变量' },
  { of: 'sync.TLS', label: 'clear', kind: 'method', detail: '清空线程局部变量' },

  // === sync.WorkerPool members ===
  { of: 'sync.WorkerPool', label: 'submit', kind: 'method', detail: '提交任务' },
  { of: 'sync.WorkerPool', label: 'wait', kind: 'method', detail: '等待全部任务完成' },
  { of: 'sync.WorkerPool', label: 'wait_timeout', kind: 'method', detail: '带超时等待' },
  { of: 'sync.WorkerPool', label: 'stop', kind: 'method', detail: '停止工作池' },

  // === WaitGroup members ===
  { of: 'sync.WaitGroup', label: 'add', kind: 'method', detail: '增加计数 n' },
  { of: 'sync.WaitGroup', label: 'done', kind: 'method', detail: '完成一个（计数-1）' },
  { of: 'sync.WaitGroup', label: 'wait', kind: 'method', detail: '阻塞直到计数归零' },
];

export interface TypeInferenceRule {
  regex: RegExp;
  type: string;
}

export const TYPE_INFERENCE_RULES: TypeInferenceRule[] = [
  { regex: /=\s*\d+\.\d+/, type: 'float' },
  { regex: /=\s*\d+\.\d*(?:[eE][+-]?\d+)?/, type: 'float' },
  { regex: /=\s*\d+$/, type: 'int' },
  { regex: /=\s*0x[0-9a-fA-F]+/, type: 'int' },
  { regex: /=\s*0b[01]+/, type: 'int' },
  { regex: /=\s*true|false/, type: 'bool' },
  { regex: /=\s*".*"/, type: 'string' },
  { regex: /=\s*b".*"/, type: 'bytes' },
  { regex: /=\s*\[.*\]/, type: 'list' },
  { regex: /=\s*\{.*\}/, type: 'dict' },
  { regex: /=\s*nil/, type: 'nil' },
  { regex: /=\s*ipv4\(/, type: 'ipv4' },
  { regex: /=\s*ipv6\(/, type: 'ipv6' },
  { regex: /=.*socket\.Socket\(/, type: 'socket' },
  { regex: /=.*socket\.(tcp_request|udp_request|tls_request)\(/, type: 'socket' },
  { regex: /=.*sync\.Mutex\(/, type: 'sync.Mutex' },
  { regex: /=.*sync\.RWMutex\(/, type: 'sync.RWMutex' },
  { regex: /=.*sync\.Once\(/, type: 'sync.Once' },
  { regex: /=.*sync\.Cond\(/, type: 'sync.Cond' },
  { regex: /=.*sync\.Semaphore\(/, type: 'sync.Semaphore' },
  { regex: /=.*sync\.Atomic\(/, type: 'sync.Atomic' },
  { regex: /=.*sync\.Chan\(/, type: 'sync.Chan' },
  { regex: /=.*sync\.TLS\(/, type: 'sync.TLS' },
  { regex: /=.*sync\.WorkerPool\(/, type: 'sync.WorkerPool' },
  { regex: /=.*sync\.WaitGroup\(/, type: 'sync.WaitGroup' },
  { regex: /=.*json\.parse/, type: 'dict' },
  { regex: /=.*yaml\.parse/, type: 'dict' },
];

export const SNIPPETS: CompletionItemMeta[] = [
  { label: 'pkgmain', kind: 'snippet', detail: 'package main 入口', insertText: 'package main\n\nfunc main() {\n\t${0}\n}\n', sortKey: 1 },
  { label: 'func', kind: 'snippet', detail: '函数定义', insertText: 'func ${1:name}(${2:args}) {\n\t${0}\n}\n', sortKey: 5 },
  { label: 'for', kind: 'snippet', detail: 'for-in 循环', insertText: 'for ${1:item} in ${2:list} {\n\t${0}\n}\n', sortKey: 5 },
  { label: 'if', kind: 'snippet', detail: 'if 条件', insertText: 'if ${1:cond} {\n\t${0}\n}\n', sortKey: 5 },
  { label: 'match', kind: 'snippet', detail: 'match 模式匹配', insertText: 'match ${1:val} {\n\t${2:pattern} => { ${3:body} }\n\t_ => { ${0:default} }\n}\n', sortKey: 5 },
  { label: 'warp', kind: 'snippet', detail: '并发线程', insertText: 'let ${1:h} = warp {\n\t${0}\n}\n${1:h}.await()\n', sortKey: 5 },
  { label: 'method', kind: 'snippet', detail: 'struct 方法（this）', insertText: 'func this.${1:name}(${2:args}) {\n\t${0}\n}\n', sortKey: 5 },
  { label: 'ternary', kind: 'snippet', detail: '三元表达式', insertText: '${1:cond} ? ${2:a} : ${3:b}', sortKey: 5 },
  { label: 'range', kind: 'snippet', detail: '区间遍历 0..n', insertText: 'for ${1:i} in ${2:0}..${3:n} {\n\t${0}\n}\n', sortKey: 5 },
  { label: 'multiret', kind: 'snippet', detail: '多返回值', insertText: 'func ${1:name}() {\n\treturn ${2:a}, ${3:b}\n}\nlet ${4:x}, ${5:y} = ${1:name}()\n', sortKey: 5 },
  { label: 'defer', kind: 'snippet', detail: '延迟执行', insertText: 'defer func() {\n\t${0}\n}()\n', sortKey: 5 },
  { label: 'shell', kind: 'snippet', detail: 'Shell 命令', insertText: '`${1:command}`', sortKey: 5 },
  { label: 'struct', kind: 'snippet', detail: '结构体定义', insertText: 'struct ${1:Name} {\n\t${2:field}: ${3:type}\n}\n', sortKey: 5 },
  { label: 'import', kind: 'snippet', detail: '导入单个标准库模块', insertText: 'import "${1:string}"\n', sortKey: 5 },
  { label: 'importlist', kind: 'snippet', detail: '导入多个模块（列表）', insertText: 'import [\n\t"${1:string}",\n\t"${2:io}",\n]\n', sortKey: 5 },
  { label: 'importfiles', kind: 'snippet', detail: '导入脚本文件 / 目录通配', insertText: 'import [\n\t"${1:lib/util}",\n]\n', sortKey: 5 },
  { label: 'catchensure', kind: 'snippet', detail: 'catch + ensure 清理块', insertText: 'catch {\n\t${1:body}\n} ensure {\n\t${0:cleanup()}\n}\n', sortKey: 5 },
  { label: 'socketclient', kind: 'snippet', detail: 'socket TCP 客户端', insertText: 'let s = socket.Socket("tcp")\ns.connect("${1:127.0.0.1}", ${2:8080})\n${0}\n', sortKey: 5 },
  { label: 'socketrequest', kind: 'snippet', detail: '一行 TCP 请求', insertText: 'let resp = binary.UTF8(socket.tcp_request("${1:127.0.0.1}", ${2:80}, "${3:GET / HTTP/1.1\\r\\n\\r\\n}"))\n', sortKey: 5 },
  { label: 'mutex', kind: 'snippet', detail: 'sync.Mutex 临界区', insertText: 'let m = sync.Mutex()\nm.lock()\n${0}\nm.unlock()\n', sortKey: 5 },
];

/** 构建所有补全项 */
export function buildAllCompletions(): CompletionItemMeta[] {
  return [...KEYWORDS, ...TYPES, ...BUILTIN_FUNCTIONS, ...SNIPPETS];
}

/** 构建悬停文档（markdown） */
export function buildHoverDoc(m: CompletionItemMeta): string {
  const kindLabel: Record<string, string> = {
    keyword: '关键字', type: '类型', constant: '常量',
    builtin: '内置函数', method: '方法', property: '属性', snippet: '代码片段',
  };
  const prefix = kindLabel[m.kind] || m.kind;
  const doc = m.documentation || m.detail;
  return `**${m.label}** — ${prefix}\n\n${doc}`;
}
